//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIBasicAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public int Empid { get; set; }
        public string EmpName { get; set; }
    }
}
